### PR TITLE
feat: Pdf subfolder

### PR DESCRIPTION
**Pull request by mickster04**
So the plan is to allow subfolders inside the PDF folder, so that mass amounts of PDF can be manged, organised and accessed nicely.
This is only the API as I can't do EFB work (skill issue).

I have added optional "directoryname" query params to the urls for the pdfs.
It is expected the EFB will keep a track of what the hierarchy is as APIs are stateless.

It is backwards compatible with current build.

E.G.

pdf folder
` NZ(folder) 
- NZHN (folder)
 -- NZHNfile1.pdf
 -- NZHNfile2.pdf
 - NZAA (folder)
 -- NZAAfile1.pdf
 -- NZAAfile2.pdf
RootFile.pdf`
 
to get NZHN1.pdf 
`URL: ...pdf?directoryname=NZ/NZHN&filename=NZHN1.pdf`

to list all NZAA
`URL: ...pdf/list?directoryname=NZ/NZAA`

to get rootfile.pdf
`URL: ...pdf?filename=RootFile.pdf`

My questions to maintainers
a) have i met style guides for coding typescript
b) is this as easy to read as before (the if else on `directoryname === undefined` felt odd)
c) I don't see any tests, so am I all good with just this? 
d) I haven't implemented subfolders for images, should I?

I couldn't work out a good way to supply directory names as a list of folders rather than preformatted with the /, so LMK if there is a better way to do this. I see there is a checkFilePathSafety method which I assume covers me here?

### CODE REVIEW

**Comment by mickster04** [comment]
I've been thinking about this. I was wondering if instead of a list of strings for pdf queries, simbridge should instead return an object stating a) parent folder(s) b) filename (as current) and c) filetype, so that the the need for pdf vs image isn't a thing anymore? the recipient device can know how to render any file based on it's file type, therefore users can store images and pdfs in the resources folder without the need for separating out the filetypes manually?

**Comment by Lucky38i** [comment]
Once we have these changes reflected in the EFB then we can merge this

**Comment by Lucky38i** [comment]
Any updates on this? @mickster04

**Comment by mickster04** [comment]
I can't do efb dev because a) skill issue, I can't do typescript and b) I can't get the dev env to work.

**Comment by mickster04** [comment]
Super grateful. I implemented it such that it won't break current build so could be merged in before the EFB is updated, if that's appropriate.

**Pull request merged**
